backend:
  name: github
  repo: gauthamu52-hub/dentara-website
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: https://dentara.co.in
display_url: https://dentara.co.in

collections:

  - name: "blogs"
    label: "Blogs"
    folder: "content/blogs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"

      - label: "Featured Image"
        name: "image"
        widget: "image"
        required: false

      - label: "Short Description"
        name: "description"
        widget: "text"

      - label: "SEO Title"
        name: "seo_title"
        widget: "string"
        required: false

      - label: "SEO Description"
        name: "seo_description"
        widget: "text"
        required: false

      - label: "Blog Content"
        name: "body"
        widget: "markdown"

  - name: "gallery"
    label: "Clinic Photos"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Photo"
        name: "image"
        widget: "image"

      - label: "Photo Title"
        name: "title"
        widget: "string"

      - label: "Description"
        name: "description"
        widget: "text"
        required: false
